In [1]:
!unzip bustime_chattanooga_jan_2022.json.zip

Archive:  bustime_chattanooga_jan_2022.json.zip
  inflating: bustime_chattanooga_jan_2022.json

In [1]:
import json
with open("bustime_chattanooga_jan_2022.json", "r") as f:
    data = json.load(f)

dated = []
for record in data:
    tmstmp = record["tmstmp"]
    if "20220111" in tmstmp:

        dated.append(record)

In [2]:
data =dated
dated = []
for record in data:
    trp = record["origtatripno"]
    if trp:
        dated.append(trp)

unique_trp = list(set(dated))
unique_trp.sort()

print(len(unique_trp))

712

In [3]:
import pandas as pd
import json
df = pd.read_csv("trips.txt", sep=",")

trips = unique_trp
trips = list(map(int, trips))

df_fil  = pd.DataFrame(columns = df.columns)

indices = []
for trip in trips:
    for index, row in df.iterrows():       
        if trip == int(row['trip_id']/1000):
            
            indices.append(index)
            df_fil.append(row, ignore_index=True)
            break


df_fil = df.iloc[indices]
print(df_fil.head())
# df_fil.to_csv('df_fil_19.csv', index=False)

FileNotFoundError: ignored

In [4]:
import pandas as pd
df = pd.DataFrame(data)

In [8]:
for i, row in df.iterrows():
  df
df('origtatripno')

,_id,vid,tmstmp,lat,lon,hdg,pid,rt,des,pdist,...,srvtmstmp,dly,spd,tablockid,tatripid,zone,mode,psgld,timestamp,geometry
origtatripno,,,,,,,,,,,,,,,,,,,,,
204888,186,186,186,186,186,186,186,186,7,186,...,186,186,186,186,186,0,186,186,186,186
204889,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,0,54,54,54,54
204890,70,70,70,70,70,70,70,70,70,70,...,70,70,70,70,70,0,70,70,70,70
204891,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,0,66,66,66,66
204892,86,86,86,86,86,86,86,86,86,86,...,86,86,86,86,86,0,86,86,86,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206975,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,0,30,30,30,30
207272,60,60,60,60,60,60,60,60,60,60,...,60,60,60,60,60,0,60,60,60,60
207273,47,47,47,47,47,47,47,47,47,47,...,47,47,47,47,47,0,47,47,47,47
207274,46,46,46,46,46,46,46,46,46,46,...,46,46,46,46,46,0,46,46,46,46
207275,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,0,39,39,39,39

In [9]:
gb = df.groupby('origtatripno')    
trips = [gb.get_group(x) for x in gb.groups]

In [17]:
trips[1].columns

Index(['_id', 'vid', 'tmstmp', 'lat', 'lon', 'hdg', 'pid', 'rt', 'des',
       'pdist', 'oid', 'rid', 'or', 'tripdyn', 'srvtmstmp', 'dly', 'spd',
       'tablockid', 'tatripid', 'origtatripno', 'zone', 'mode', 'psgld',
       'timestamp', 'geometry'],
      dtype='object')

In [23]:
details = pd.DataFrame()
c = 1
for trip in trips:
  details.loc[c, 'tripd_id'] = trip.origtatripno.iloc[0]
  details.loc[c, 'clever_start_time'] = trip.tmstmp.iloc[0]
  details.loc[c, 'clever_start_timestamp'] = trip.timestamp.iloc[0]
  details.loc[c, 'clever_end_time'] = trip.tmstmp.iloc[-1]
  details.loc[c, 'clever_end_timestamp'] = trip.timestamp.iloc[-1]
  c+=1

In [30]:
details.sort_values(['clever_start_timestamp']).reset_index().drop(['index'], axis=1)[3:].to_csv('20220111_clever_times.csv')